# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
      time: "09:00"
      timezone: "Europe/Helsinki"

  - package-ecosystem: "pip"
    directory: "/functions"
    schedule:
      interval: "monthly"
      day: "sunday"
      time: "09:00"
      timezone: "Europe/Helsinki"

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'sunday'
      time: '09:00'
      timezone: 'Europe/Helsinki'
