name: App linting, typing, tests and coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write
  issues: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Set up uv
        uses: astral-sh/setup-uv@v7.3.0
        with:
          python-version: '3.14'
          enable-cache: true

      - name: Set up just
        uses: extractions/setup-just@v3.0.0

      - name: Install dependencies
        run: just install

      - name: Run linting checks
        run: just lint

      - name: Run typing checks
        run: just typing

      - name: Run test coverage
        run: just cov

      - name: Upload coverage report
        uses: actions/upload-artifact@v6.0.0
        with:
          name: coverage-report
          path: htmlcov

      - name: Pytest coverage reporter (PR only)
        if: ${{ github.event_name == 'pull_request' }}
        uses: dima-engineer/pytest-reporter@v4.2.0
        with:
          pytest-root-dir: app
          pytest-tests-dir: tests
          cov-omit-list: tests/*
          cov-threshold-single: 75
          cov-threshold-total: 75
          async-tests: true
          uv-version: latest
